# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-18 17:23
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_link', models.CharField(max_length=20, verbose_name='لینک فعال سازی')),
                ('user_id', models.IntegerField(verbose_name='شناسه کاربر')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن نظر')),
                ('star_number', models.IntegerField(choices=[(0, 'بدون ستاره'), (1, 'یک ستاره'), (2, 'دو ستاره'), (3, 'سه ستاره'), (4, 'چهار ستاره'), (5, 'پنج ستاره')], max_length=1)),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات',
            },
        ),
        migrations.CreateModel(
            name='Commsion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.BigIntegerField(default=0, verbose_name='مبلغ')),
                ('start_date', models.DateField(auto_now=True, verbose_name='از تاریخ')),
                ('end_date', models.DateField(auto_now=True, verbose_name='تا تاریخ')),
                ('status', models.BooleanField(default=False, verbose_name='وضعیت پرداخت')),
            ],
            options={
                'verbose_name': 'کارمزد',
                'verbose_name_plural': 'کارمزدها',
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('gender', models.CharField(choices=[('man', 'مرد'), ('women', 'زن')], max_length=10, verbose_name='جنسیت')),
                ('first_phone', models.IntegerField(max_length=15, verbose_name='تلفن ثابت')),
                ('second_phone', models.IntegerField(max_length=15, verbose_name='تلفن جایگزین')),
                ('cell_phone', models.IntegerField(max_length=15, verbose_name='تلفن همراه')),
                ('active', models.BooleanField(default=False, verbose_name='فعال شده')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='نام')),
                ('star_number', models.IntegerField(choices=[(0, 'بدون ستاره'), (1, 'یک ستاره'), (2, 'دو ستاره'), (3, 'سه ستاره'), (4, 'چهار ستاره'), (5, 'پنج ستاره')], max_length=1, verbose_name='ستاره')),
                ('average_star_number', models.FloatField(default=0, verbose_name='میانگین ستاره')),
                ('critic_number', models.IntegerField(default=0, verbose_name='تعداد نظردهندگان')),
                ('grade', models.IntegerField(default=0, verbose_name='رتبه در رده بندی')),
                ('credit_number', models.IntegerField(verbose_name='شماره حساب')),
                ('address', models.TextField(max_length=200, verbose_name='آدرس')),
                ('city', models.CharField(max_length=20, verbose_name='شهر')),
                ('phone_number', models.BigIntegerField(verbose_name='شماره تلفن')),
                ('lake', models.BooleanField(verbose_name='منظره ساحل')),
                ('pool', models.BooleanField(verbose_name=' استخر')),
                ('sport', models.BooleanField(verbose_name='امکانات ورزشی')),
                ('breakfast', models.BooleanField(verbose_name='صبحانه')),
                ('wifi', models.BooleanField(verbose_name='اینترنت در لابی')),
                ('parking', models.BooleanField(verbose_name='پارکینگ')),
                ('cafe', models.BooleanField(verbose_name='کافه رستوران')),
            ],
            options={
                'verbose_name': 'هتل',
                'verbose_name_plural': 'هتل ها',
            },
        ),
        migrations.CreateModel(
            name='HotelPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photo\\hotelphotos', verbose_name='عکس')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manage.Hotel', verbose_name='هتل')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(verbose_name='تاریخ پایان')),
                ('request_time', models.DateTimeField(auto_now=True, verbose_name='زمان درخواست')),
                ('total_cost', models.BigIntegerField(verbose_name='هزینه کل')),
                ('status', models.IntegerField(default=0, verbose_name='وضعیت درخواست')),
            ],
            options={
                'verbose_name': 'درخواست رزرو',
                'verbose_name_plural': 'درخواست های رزرو',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, verbose_name='نوع')),
                ('cost', models.BigIntegerField(verbose_name='قیمت روزانه')),
                ('area', models.IntegerField(verbose_name='متراژ')),
                ('king_bed', models.IntegerField(verbose_name='تخت دونفره')),
                ('queen_bed', models.IntegerField(verbose_name='تخت یک نفره')),
                ('tv', models.BooleanField(verbose_name='تلویزیون')),
                ('wifi', models.BooleanField(verbose_name='اینترنت')),
                ('kitchen', models.BooleanField(verbose_name='آشپزخانه')),
                ('extra_bed', models.BooleanField(verbose_name='تخت سفری')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manage.Hotel', verbose_name='هتل')),
            ],
            options={
                'verbose_name': 'اتاق',
                'verbose_name_plural': 'اتاق ها',
            },
        ),
        migrations.CreateModel(
            name='RoomPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photo\\roomphotos', verbose_name='عکس')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manage.Room', verbose_name='اتاق')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refrence_number', models.IntegerField(max_length=7, verbose_name='شماره پیگیری')),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Manage.Reservation', verbose_name='درخواست رزرو')),
            ],
            options={
                'verbose_name': 'تراکنش',
                'verbose_name_plural': 'تراکنش ها',
            },
        ),
        migrations.CreateModel(
            name='Hotelier',
            fields=[
                ('guest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Manage.Guest')),
                ('can_edit_hotel', models.BooleanField(default=False)),
                ('can_edit_room', models.BooleanField(default=False)),
                ('can_delete_hotel', models.BooleanField(default=False)),
                ('can_delete_room', models.BooleanField(default=False)),
                ('can_add_room', models.BooleanField(default=False)),
                ('can_add_hotel', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'هتل دار',
                'verbose_name_plural': 'هتل داران',
            },
            bases=('Manage.guest',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('guest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Manage.Guest')),
            ],
            options={
                'verbose_name': 'مسافر',
                'verbose_name_plural': 'مسافران',
            },
            bases=('Manage.guest',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manage.Room', verbose_name='اتاق'),
        ),
        migrations.AddField(
            model_name='comment',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manage.Hotel', verbose_name='هتل'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manage.Passenger', verbose_name='مسافر'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='room',
            field=models.ManyToManyField(through='Manage.Reservation', to='Manage.Room', verbose_name='اتاق'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotelier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manage.Hotelier', verbose_name='هتل دار'),
        ),
        migrations.AddField(
            model_name='commsion',
            name='hotelier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manage.Hotelier', verbose_name='هتل دار'),
        ),
        migrations.AddField(
            model_name='comment',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manage.Passenger', verbose_name='مسافر'),
        ),
    ]
